# SmartSuite Services Table Field Mappings
# SOLUTION 1: EAV Projects (68b6d66b33630eb365ae54cb)
# TABLE: Services (68b7fb8ed78e0c91416c1787)
# Created: 2025-09-08

tableName: services
tableId: 68b7fb8ed78e0c91416c1787
solutionId: 68b6d66b33630eb365ae54cb

# Field mappings (human name → actual API slug)
fields:
  # Core Service Fields
  serviceName: title                    # Service Name - Record Title
  autoNumber: autonumber                # Auto Number - Prefix: "S", Leading zeros: 3
  serviceCode: servicecode1             # Service Code - Text Field (unique identifier)
  
  # Service Management
  status: svcstatus01                   # Status - Single Select (Active/Inactive/Pending)
  
  # Pricing Fields
  baseRate: baserate001                 # Base Rate - Currency (GBP)
  pricingTiers: pricingtier             # Pricing Tiers - Rich Text (formatted pricing info)
  rateOptions: rateoptions              # Rate Options - Sub-Items (structured pricing)
  
  # Relationships
  linkToProjects: slw932e3              # Link to Projects - Linked Record
  
  # System Fields
  firstCreated: first_created           # First Created - Created Time
  lastUpdated: last_updated             # Last Updated - Updated Time
  followedBy: followed_by               # Followed by - User Field
  openComments: comments_count          # Open Comments - Comments Count

# Status Options
statusOptions:
  - Active
  - Inactive
  - Pending

# Rate Options Sub-Items Structure
rateOptionsStructure:
  quantityTier:                        # Text: e.g., "100 stickers", "Standard Service", "5 hours"
  price:                               # Currency (GBP): Price for this tier
  unitType:                            # Text: e.g., "per pack", "per hour", "per project"
  notes:                               # Text Area: Additional details about this pricing tier

# Service Examples
serviceExamples:
  - name: QR Code Stickers
    tiers:
      - 100 @ £130
      - 150 @ £140
      - 200 @ £150
  - name: Video Editing
    description: Hourly rates with volume discounts
  - name: Express Services
    tiers:
      - Standard pricing
      - Rush pricing
      - Emergency pricing

# NOTES:
# - Services table for service catalog and pricing management
# - Total of 12 fields (8 user + 4 system)
# - Rate Options uses SmartSuite Sub-Items for structured pricing tiers
# - Base Rate provides standard service rate
# - Pricing Tiers allows rich text formatting for complex pricing
# - All slugs verified against EAV-Final-Table-Field-List.md
