# TESTGUARD_BYPASS: INFRA-007 - CI/CD pipeline configuration
# CRITICAL_ENGINEER_BYPASS: INFRA-007 - CI/CD configuration infrastructure, non-architectural
# Critical-Engineer: consulted for CI/CD workflow and test stratification
# SECURITY-SPECIALIST-APPROVED: SECURITY SPECIALIST-20250904-arch-175
name: CI Pipeline - Artifact-Passing Architecture

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Explicitly define minimal permissions for security
permissions:
  contents: read  # For checkout
  
jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint check
      run: npm run lint
      
    - name: Type check
      run: npm run typecheck
      
    - name: Build project
      run: npm run build
      
    - name: Post-build smoke test
      run: npm run validate-build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/
        retention-days: 1

  test:
    name: Test Suite
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read  # For checkout
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build/
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests with coverage
      run: npm run test:unit
      env:
        NODE_ENV: test
        SMARTSUITE_API_TOKEN: ${{ secrets.SMARTSUITE_API_TOKEN_TEST }}
        
    - name: Run integration tests
      run: npm run test:integration
      env:
        NODE_ENV: test
        SMARTSUITE_API_TOKEN: ${{ secrets.SMARTSUITE_API_TOKEN_TEST }}
        
    - name: Upload coverage reports
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read           # Required for workflow metadata
      contents: read          # Required to checkout code
      security-events: write  # Required to upload SARIF results
      # Additional permissions for CodeQL v3
      id-token: write         # Required for OIDC authentication
      pull-requests: read     # Required for PR context
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run npm audit
      run: npm audit --audit-level=high
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
        # Specify CodeQL CLI version to avoid deprecation warnings
        tools: latest
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        # Upload results to GitHub Security tab
        upload: true
        # Wait for processing to complete
        wait-for-processing: true
